### ISSUE TITLE
Transaction is generated with a typo

### ISSUE THREAD

**Issue by schabluk** [tokenika/secure-bp-voting#15]
In section authorization there is "permissaion" instead of "permission":

```
               "authorization": [
                    {
                        "actor": "abcydgmzqhfge",
                        "permissaion": "active"
                    }
                ],
```

**Comment by noisy** [comment]
@schabluk we didn't modify a code of eos.js library, so if this error occasionally occurs, its means that it is a bug in https://github.com/eosio/eosjs

Nevertheless, could you elaborate this a little bit more? How often something like this happen?

**Comment by schabluk** [comment]
I have downloaded eos.js locally, maybe the file got corrupted.

**Comment by noisy** [comment]
@schabluk please be aware, that if you are using our instruction, you do not have to manually download `eos.js`, because a browser can do it for you, when you will save a page by `Save as...`

Please take a look on: https://github.com/tokenika/secure-bp-voting/issues/16#issuecomment-397282762

**Comment by schabluk** [comment]
@noisy I don't trust my browser. It could alter the content of eos.js while "Saving as" and then, the altered eos.js could generate a transaction that would clean my account, no?
