### ISSUE TITLE
Step 3 - Failure no balance object found with delegatebw 

### ISSUE THREAD

**Issue by Liryna** [tokenika/secure-bp-voting#4]
Hi @noisy,

As first, thank you for your work 👍 !

During the step 3 when sending the json formated by the offline step 2, I get an error looking at the data format seems like:
```
{"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[{"message":"assertion failure with message: no balance object found","file":"wasm_interface.cpp","line_number":930,"method":"eosio_assert"},{"message":"","file":"apply_context.cpp","line_number":62,"method":"exec_one"}]}}
```

While removing the delegatebw tr I get a correct answer from the server. 
https://github.com/tokenika/secure-bp-voting/blob/master/2_generate_transaction.html#L57-L63

Here is my delegatebw  param:
```
Main Token Symbol: EOS
Stake Net Quantity: 1
Stake CPU Quantity: 1
```

Am I doing something wrong here ? Is the delegatebw  mandatory since eosjs 14.1.1 (https://github.com/tokenika/secure-bp-voting/commit/bafd471e07685be4d8f5d76e82daa165e61de7df#diff-619156110c27bddcece05fd7650497ab)?

**Comment by noisy** [comment]
@Liryna currently we decided to remove form to stake tokens from this website, to simplify whole process... and also because current chain has most of the tokens already staked.

Code with Staking is still available on `staking` branch: https://github.com/tokenika/secure-bp-voting/tree/staking

Could you confirm, that this problem still occurs?

**Comment by Liryna** [comment]
Hi @noisy ,

Yes thank you ! work perfectly !

**Comment by adeelnaqvi172** [comment]
@noisy 
![Screenshot from 2020-09-08 22-48-29](https://user-images.githubusercontent.com/53054023/92510922-05e82380-f226-11ea-9db8-ca79e3c6912b.png)
 
i am facing this one please help
