### ISSUE TITLE
How to use this to make a vote on the main net?

### ISSUE THREAD

**Issue by Aranad** [tokenika/secure-bp-voting#6]
There's no info anywhere about what to use for API endpoint for voting on the main net?

**Comment by brockz** [comment]
Same here.

**Comment by noisy** [comment]
@Aranad @brockz you can use any API endpoint for desired chain which supports https and it is configured in a proper way.

To simplify a process, we have just added 2 suggested API endpoints:

![public_api_endpoints](https://user-images.githubusercontent.com/201263/41225160-7e3d920a-6d6e-11e8-8498-86e577197cae.png)

You can choose them from dropdown list **but you can still use other api endpoints** of your own choice.

New api endpoints can be added to a list, as soon as community will notify us about them.
