### ISSUE TITLE
Unable to Fetch Infromations from Endpoint API

### ISSUE THREAD

**Issue by brockz** [tokenika/secure-bp-voting#7]
Hello

I tried using  https://mainnet.eoscanada.com Endpoint  URL on the  1_get_blockchain_data.html Site.
It returns with an Failed to Fetch Error.

How can that be accomplished ?

Br Stefan

**Comment by noisy** [comment]
Hello @brockz,

It looks like endpoint https://mainnet.eoscanada.com/ is not configured in a way to support requests from 3rd party websites.

This can be enabled by 

`access-control-allow-origin = *` 

in ` config.ini` in nodeos.

We would more than happy, to add this node to [current suggested list of API endpoints](https://github.com/tokenika/secure-bp-voting/issues/6), as soon as they will change their config, and we will be able to confirm that it's working.
